Data Preprocessing on Breast Cancer Dataset - 4/29/2026 - derave1577

In [1]:
# Import necessary libraries
import pandas as pd
from datetime import datetime
from IPython.display import display, Markdown
todays_date = datetime.now().strftime("%Y-%m-%d")
student_id = "derave1577"
# Load the Breast Cancer dataset
data = pd.read_csv('breastCancerDataset.csv')
display(Markdown("### Step 1: Load the Dataset"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))
# Get a concise summary of the DataFrame
print(data.info())
# Get descriptive statistics that summarize the central tendency, dispersion, and shape of the dataset's numerical features
display(data.describe())

### Step 1: Load the Dataset

Date: 2026-04-29

Student ID: derave1577

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  569 non-null    int64
 1   Diagnosis           569 non-null    str
 2   radius1             569 non-null    float64
 3   texture1            569 non-null    float64
 4   perimeter1          569 non-null    float64
 5   area1               569 non-null    float64
 6   smoothness1         569 non-null    float64
 7   compactness1        569 non-null    float64
 8   concavity1          569 non-null    float64
 9   concave_points1     569 non-null    float64
 10  symmetry1           569 non-null    float64
 11  fractal_dimension1  569 non-null    float64
 12  radius2             569 non-null    float64
 13  texture2            569 non-null    float64
 14  perimeter2          569 non-null    float64
 15  area2               569 non-null    float64
 16  smoothness2         569 non-null    float64
 17  compactness2        569 non-null    float64
 18  concavity2          569 non-null    float64
 19  concave_points2     569 non-null    float64
 20  symmetry2           569 non-null    float64
 21  fractal_dimension2  569 non-null    float64
 22  radius3             569 non-null    float64
 23  texture3            569 non-null    float64
 24  perimeter3          569 non-null    float64
 25  area3               569 non-null    float64
 26  smoothness3         569 non-null    float64
 27  compactness3        569 non-null    float64
 28  concavity3          569 non-null    float64
 29  concave_points3     569 non-null    float64
 30  symmetry3           569 non-null    float64
 31  fractal_dimension3  569 non-null    float64
dtypes: float64(30), int64(1), str(1)
memory usage: 142.4 KB
None

,ID,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,284.000000,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,164.400426,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,0.000000,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,142.000000,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,284.000000,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,426.000000,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,568.000000,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [2]:
from sklearn.preprocessing import StandardScaler
from scipy.stats import zscore
from sklearn.model_selection import train_test_split
display(Markdown("### Step 2: Preprocessing Data"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))
# Initialize the StandardScaler
scaler = StandardScaler()
# Select numerical features for scaling
numerical_features = data.drop(columns=['ID', 'Diagnosis']).columns.tolist()
# Apply scaling
scaled_data = data.copy()
scaled_data[numerical_features] = scaler.fit_transform(data[numerical_features])
# Calculate z-scores for the scaled numerical features
for feature in numerical_features:
    scaled_data[f'{feature}_Z'] = zscore(scaled_data[feature])
# Remove outliers based on z-scores outside the range [-2, 2]
for feature in numerical_features:
    scaled_data = scaled_data[(scaled_data[f'{feature}_Z'] >= -2) & (scaled_data[f'{feature}_Z'] <= 2)]
# Drop the z-score columns as they are no longer needed
scaled_data = scaled_data.drop(columns=[f'{feature}_Z' for feature in numerical_features])
# Recalculate the scaling on the cleaned data
scaled_data[numerical_features] = scaler.fit_transform(scaled_data[numerical_features])
# Display the first few rows to verify the changes
display(scaled_data.head())
# Update the main dataframe to use scaled features
data = scaled_data
# Preparing features (X) and target variable (y) from the prepared dataset
X = data.drop(columns=['ID', 'Diagnosis'])
y = data['Diagnosis']
# Splitting the data into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Display the sizes of the training and test sets to verify the split
print(f"Training set size: {X_train.shape[0]} samples")
print(f"Test set size: {X_test.shape[0]} samples")

### Step 2: Preprocessing Data

Date: 2026-04-29

Student ID: derave1577

,ID,Diagnosis,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
1,1,M,2.589372,-0.165653,2.467692,2.964460,-0.783017,-0.260704,0.510852,1.231328,...,2.693001,-0.217041,2.413448,3.179163,-0.281090,-0.243296,0.213097,1.777277,-0.117499,0.843813
4,4,M,2.485703,-1.156920,2.587928,2.847463,0.589734,1.343715,2.795144,2.522858,...,2.006952,-1.546149,2.140321,2.164783,0.461134,-0.058932,1.377969,1.299066,-1.060944,-0.221101
6,6,M,1.730398,0.473036,1.740811,1.810630,0.089509,0.638671,1.041317,1.376261,...,2.102159,0.621047,2.181704,2.247318,0.832245,0.468108,1.219122,1.923793,0.647523,0.379218
7,7,M,0.049476,0.718685,0.134021,-0.053653,2.230683,2.282786,0.649842,0.840803,...,0.472442,0.715701,0.418796,0.359667,1.989240,1.576296,0.405772,1.158655,0.972596,3.112844
10,10,M,0.904747,1.415173,0.817180,0.833505,-1.019454,-0.614707,-0.597575,-0.166538,...,1.068885,1.847613,0.965049,1.033258,-0.592168,-0.558919,-0.490679,0.022140,0.366445,0.452300

Training set size: 267 samples
Test set size: 115 samples

In [3]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import GridSearchCV
display(Markdown("### Step 3: Training the SVM Model"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))
# Initialize the SVM model
svm = SVC()
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
display(Markdown("Accuracy Score: "))
print(accuracy_score(y_test, y_pred))
display(Markdown("Classification Report: "))
print(classification_report(y_test, y_pred))

### Step 3: Training the SVM Model

Date: 2026-04-29

Student ID: derave1577

Accuracy Score:

0.9739130434782609

Classification Report:

              precision    recall  f1-score   support

           B       0.99      0.97      0.98        80
           M       0.94      0.97      0.96        35

    accuracy                           0.97       115
   macro avg       0.97      0.97      0.97       115
weighted avg       0.97      0.97      0.97       115

In [4]:
# Initialize a new model
svm1 = SVC()
# Define the parameter grid for hyperparameter tuning
param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly']
}
# Initialize GridSearchCV with the SVM model and parameter grid
grid_search = GridSearchCV(svm1, param_grid, refit=True, verbose=2, cv=5)
# Fit the model to the training data
grid_search.fit(X_train, y_train)
# Display the best parameters and best score
print(f"Best Parameters: {grid_search.best_params_}")
print(f"Best Score: {grid_search.best_score_}")
# Make predictions on the test data
y_pred = grid_search.predict(X_test)
# Print the classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))
# Print the confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] END ...............................C=0.1, kernel=linear; total time=   0.0s
[CV] END ...............................C=0.1, kernel=linear; total time=   0.0s
[CV] END ...............................C=0.1, kernel=linear; total time=   0.0s
[CV] END ...............................C=0.1, kernel=linear; total time=   0.0s
[CV] END ...............................C=0.1, kernel=linear; total time=   0.0s
[CV] END ..................................C=0.1, kernel=rbf; total time=   0.0s
[CV] END ..................................C=0.1, kernel=rbf; total time=   0.0s
[CV] END ..................................C=0.1, kernel=rbf; total time=   0.0s
[CV] END ..................................C=0.1, kernel=rbf; total time=   0.0s
[CV] END ..................................C=0.1, kernel=rbf; total time=   0.0s
[CV] END .................................C=0.1, kernel=poly; total time=   0.0s
[CV] END .................................C=0.1, kernel=poly; total time=   0.0s
[CV] END .................................C=0.1, kernel=poly; total time=   0.0s
[CV] END .................................C=0.1, kernel=poly; total time=   0.0s
[CV] END .................................C=0.1, kernel=poly; total time=   0.0s
[CV] END .................................C=1, kernel=linear; total time=   0.0s
[CV] END .................................C=1, kernel=linear; total time=   0.0s
[CV] END .................................C=1, kernel=linear; total time=   0.0s
[CV] END .................................C=1, kernel=linear; total time=   0.0s
[CV] END .................................C=1, kernel=linear; total time=   0.0s
[CV] END ....................................C=1, kernel=rbf; total time=   0.0s
[CV] END ....................................C=1, kernel=rbf; total time=   0.0s
[CV] END ....................................C=1, kernel=rbf; total time=   0.0s
[CV] END ....................................C=1, kernel=rbf; total time=   0.0s
[CV] END ....................................C=1, kernel=rbf; total time=   0.0s
[CV] END ...................................C=1, kernel=poly; total time=   0.0s
[CV] END ...................................C=1, kernel=poly; total time=   0.0s
[CV] END ...................................C=1, kernel=poly; total time=   0.0s
[CV] END ...................................C=1, kernel=poly; total time=   0.0s
[CV] END ...................................C=1, kernel=poly; total time=   0.0s
[CV] END ................................C=10, kernel=linear; total time=   0.0s
[CV] END ................................C=10, kernel=linear; total time=   0.0s
[CV] END ................................C=10, kernel=linear; total time=   0.0s
[CV] END ................................C=10, kernel=linear; total time=   0.0s
[CV] END ................................C=10, kernel=linear; total time=   0.0s
[CV] END ...................................C=10, kernel=rbf; total time=   0.0s
[CV] END ...................................C=10, kernel=rbf; total time=   0.0s
[CV] END ...................................C=10, kernel=rbf; total time=   0.0s
[CV] END ...................................C=10, kernel=rbf; total time=   0.0s
[CV] END ...................................C=10, kernel=rbf; total time=   0.0s
[CV] END ..................................C=10, kernel=poly; total time=   0.0s
[CV] END ..................................C=10, kernel=poly; total time=   0.0s
[CV] END ..................................C=10, kernel=poly; total time=   0.0s
[CV] END ..................................C=10, kernel=poly; total time=   0.0s
[CV] END ..................................C=10, kernel=poly; total time=   0.0s
[CV] END ...............................C=100, kernel=linear; total time=   0.0s
[CV] END ...............................C=100, kernel=linear; total time=   0.0s
[CV] END ...............................C=100, kernel=linear; total time=   0.0s
[CV] END ...............................C=100, kernel=linear; total time=   0.0s
[CV] END ...............................C=100, kernel=linear; total time=   0.0s
[CV] END ..................................C=100, kernel=rbf; total time=   0.0s
[CV] END ..................................C=100, kernel=rbf; total time=   0.0s
[CV] END ..................................C=100, kernel=rbf; total time=   0.0s
[CV] END ..................................C=100, kernel=rbf; total time=   0.0s
[CV] END ..................................C=100, kernel=rbf; total time=   0.0s
[CV] END .................................C=100, kernel=poly; total time=   0.0s
[CV] END .................................C=100, kernel=poly; total time=   0.0s
[CV] END .................................C=100, kernel=poly; total time=   0.0s
[CV] END .................................C=100, kernel=poly; total time=   0.0s
[CV] END .................................C=100, kernel=poly; total time=   0.0s
Best Parameters: {'C': 0.1, 'kernel': 'linear'}
Best Score: 0.9626135569531797
Classification Report:
              precision    recall  f1-score   support

           B       0.99      0.99      0.99        80
           M       0.97      0.97      0.97        35

    accuracy                           0.98       115
   macro avg       0.98      0.98      0.98       115
weighted avg       0.98      0.98      0.98       115

Confusion Matrix:
[[79  1]
 [ 1 34]]

In [5]:
display(Markdown("### Step 4: Training the Best SVM Model"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))
# Initialize the SVM model
best_svm = grid_search.best_estimator_
best_pred = best_svm.predict(X_test)
display(Markdown("Accuracy Score: "))
print(accuracy_score(y_test, best_pred))
display(Markdown("Classification Report: "))
print(classification_report(y_test, best_pred))

### Step 4: Training the Best SVM Model

Date: 2026-04-29

Student ID: derave1577

Accuracy Score:

0.9826086956521739

Classification Report:

              precision    recall  f1-score   support

           B       0.99      0.99      0.99        80
           M       0.97      0.97      0.97        35

    accuracy                           0.98       115
   macro avg       0.98      0.98      0.98       115
weighted avg       0.98      0.98      0.98       115

In [11]:
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
display(Markdown("### Step 5: Training the XGBoost Classifier Model"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))
# Split the data into features and target variable for classification
X_clf = data.drop(columns=['ID', 'Diagnosis'])
y_clf = data['Diagnosis']
# Encode the labels B, M to 0, 1
encoder = LabelEncoder()
y_clf_encoded = encoder.fit_transform(y_clf)
# Split the data into training and testing sets
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X_clf, y_clf_encoded, test_size=0.3, random_state=42)
# Initialize the XGBoost Regressor
xgb_clf = xgb.XGBClassifier()
xgb_clf.fit(X_train_clf, y_train_clf)
y_pred_clf = xgb_clf.predict(X_test_clf)
display(Markdown("Accuracy Score: "))
print(accuracy_score(y_test_clf, y_pred_clf))
display(Markdown("Classification Report: "))
print(classification_report(y_test_clf, y_pred_clf))

### Step 5: Training the XGBoost Classifier Model

Date: 2026-04-29

Student ID: derave1577

Accuracy Score:

0.9826086956521739

Classification Report:

              precision    recall  f1-score   support

           0       0.99      0.99      0.99        80
           1       0.97      0.97      0.97        35

    accuracy                           0.98       115
   macro avg       0.98      0.98      0.98       115
weighted avg       0.98      0.98      0.98       115

In [16]:
display(Markdown("### Step 6: Applying GridSearchCV for XGBoost Hyperparameter Training"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))
# Define the parameter grid for hyperparameter tuning
param_grid = {
    'n_estimators': [50, 100],
    'learning_rate': [0.1, 0.2],
    'max_depth': [3, 4]
}
# Initialize the XGBoost Regressor
xgb_clf1 = xgb.XGBClassifier()
# Initialize GridSearchCV with the XGBoost Regressor and parameter grid
grid_search_clf = GridSearchCV(xgb_clf1, param_grid, refit=True, verbose=2, cv=5)
# Fit the model to the training data
grid_search_clf.fit(X_train_clf, y_train_clf)
# Display the best parameters and best score
print(f"Best Parameters: {grid_search_clf.best_params_}")
print(f"Best Score: {grid_search_clf.best_score_}")
best_clf = grid_search_clf.best_estimator_
best_pred_clf = best_clf.predict(X_test_clf)
display(Markdown("Accuracy Score: "))
print(accuracy_score(y_test_clf, best_pred_clf))
display(Markdown("Classification Report: "))
print(classification_report(y_test_clf, best_pred_clf, target_names=encoder.classes_))

### Step 6: Applying GridSearchCV for XGBoost Hyperparameter Training

Date: 2026-04-29

Student ID: derave1577

Fitting 5 folds for each of 8 candidates, totalling 40 fits
[CV] END ....learning_rate=0.1, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.1, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.1, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.1, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.1, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ...learning_rate=0.1, max_depth=3, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.1, max_depth=3, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.1, max_depth=3, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.1, max_depth=3, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.1, max_depth=3, n_estimators=100; total time=   0.0s
[CV] END ....learning_rate=0.1, max_depth=4, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.1, max_depth=4, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.1, max_depth=4, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.1, max_depth=4, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.1, max_depth=4, n_estimators=50; total time=   0.0s
[CV] END ...learning_rate=0.1, max_depth=4, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.1, max_depth=4, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.1, max_depth=4, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.1, max_depth=4, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.1, max_depth=4, n_estimators=100; total time=   0.0s
[CV] END ....learning_rate=0.2, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.2, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.2, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.2, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.2, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ...learning_rate=0.2, max_depth=3, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.2, max_depth=3, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.2, max_depth=3, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.2, max_depth=3, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.2, max_depth=3, n_estimators=100; total time=   0.0s
[CV] END ....learning_rate=0.2, max_depth=4, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.2, max_depth=4, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.2, max_depth=4, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.2, max_depth=4, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.2, max_depth=4, n_estimators=50; total time=   0.0s
[CV] END ...learning_rate=0.2, max_depth=4, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.2, max_depth=4, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.2, max_depth=4, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.2, max_depth=4, n_estimators=100; total time=   0.0s
[CV] END ...learning_rate=0.2, max_depth=4, n_estimators=100; total time=   0.0s
Best Parameters: {'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 50}
Best Score: 0.9439552760307478

Accuracy Score:

0.9652173913043478

Classification Report:

              precision    recall  f1-score   support

           B       0.96      0.99      0.98        80
           M       0.97      0.91      0.94        35

    accuracy                           0.97       115
   macro avg       0.97      0.95      0.96       115
weighted avg       0.97      0.97      0.96       115